matrix:
    include:
        - language: php
          services:
              - docker

          php:
              #- '7.2'
              - '7.3'
              #- nightly

          before_script:
              - make install SUDO=""
              - mkdir -p ./var && chmod 777 ./var -R

          script:
              - make test_api SUDO=""
              - make coverage
              - cat ./var/log/prod.log

        - language: python
          services: docker
          python: 3.6

          before_script:
              - make build@x86_64 build_bahub@x86_64

          script:
              - cd client && make run_test_containers test
